# Generated by Django 5.1.5 on 2025-01-27 20:43

import devices.constants
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('channel_type', models.CharField(choices=devices.constants.ChannelType, max_length=100)),
                ('int_value', models.IntegerField(blank=True)),
                ('int_min', models.IntegerField(blank=True)),
                ('int_max', models.IntegerField(blank=True)),
                ('str_value', models.CharField(blank=True, max_length=1000)),
                ('parameter', models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('interface', models.CharField(choices=[('DMX1', 'DMX 1')], max_length=10)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('feature_class', models.CharField(choices=devices.constants.FeatureList, max_length=100)),
                ('system', models.CharField(choices=[('DMX', 'DMX'), ('PICOM', 'PiCom')], max_length=10)),
            ],
            options={
                'verbose_name': 'Device Feature',
            },
        ),
        migrations.CreateModel(
            name='DeviceLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('system', models.CharField(choices=[('DMX', 'DMX'), ('PICOM', 'PiCom')], max_length=10)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': ('Device Library',),
                'verbose_name_plural': 'Device Library',
            },
        ),
        migrations.CreateModel(
            name='Manufacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('comments', models.TextField(blank=True, null=True, verbose_name='comments')),
            ],
        ),
        migrations.CreateModel(
            name='ChannelParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('allow_fading', models.BooleanField(default=False)),
                ('int_value', models.IntegerField(blank=True)),
                ('int_min', models.IntegerField(blank=True)),
                ('int_max', models.IntegerField(blank=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='devices.channel')),
            ],
        ),
        migrations.AddField(
            model_name='channel',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='devices.device'),
        ),
        migrations.AddField(
            model_name='channel',
            name='device_feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='devices.devicefeature'),
        ),
        migrations.AddField(
            model_name='devicefeature',
            name='device_library',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='devices.devicelibrary'),
        ),
        migrations.AddField(
            model_name='device',
            name='device_library',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='devices.devicelibrary'),
        ),
        migrations.AddField(
            model_name='devicelibrary',
            name='manufacture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='devices.manufacture'),
        ),
    ]
