# Generated by Django 5.1.5 on 2025-01-29 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devicefeature',
            old_name='device_library',
            new_name='library_device',
        ),
        migrations.RemoveField(
            model_name='librarychannel',
            name='library_device',
        ),
        migrations.AddField(
            model_name='channel',
            name='system_channel',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='librarychannel',
            name='sort_order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
