# Generated by Django 5.1.5 on 2025-02-04 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='librarychannel',
            name='startup_int',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
