# Generated by Django 5.1.5 on 2025-01-29 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_rename_device_library_devicefeature_library_device_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelparameter',
            name='int_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='channelparameter',
            name='int_min',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='channelparameter',
            name='int_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='librarychannel',
            name='int_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='librarychannel',
            name='int_min',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
