# Generated by Django 5.1.5 on 2025-02-05 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_librarychannel_startup_int'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('favorite', models.BooleanField(verbose_name='Favorite')),
                ('hex_code', models.CharField(max_length=7, verbose_name='Hex Code')),
                ('red', models.IntegerField(verbose_name='Red')),
                ('green', models.IntegerField(verbose_name='Green')),
                ('blue', models.IntegerField(verbose_name='Blue')),
                ('sort', models.IntegerField(blank=True, null=True, verbose_name='Sort')),
            ],
        ),
    ]
