# Generated by Django 5.1.5 on 2025-02-05 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_devicefeature_hide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelparameter',
            name='color',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='devices.color'),
        ),
    ]
