# Generated by Django 5.1.5 on 2025-02-05 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_alter_channelparameter_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelparameter',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='devices.color'),
        ),
    ]
